src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Log the LSN of the transaction which had 0 records in GetChanges

log LSN when we receive 0 records in transactional block

---

Dockerfile
pom.xml

This PR aims to integrate the maven docker plugin so that builds and the respective images can automatically be pushed to quay to be further used by users.

Add docker plugin to push image to quay using maven lifecycles

---

README.md

This PR updates the README file with the new information on how to build a docker image using maven commands as well as the steps for the Quickstart of the connector.

Updated readme with information to build docker image

---

src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

A newly added snapshot test was found to be stuck in an infinite loop when run - this PR adds the fix for the same.

Fix for the failing snapshot test

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/transforms/PGCompatible.java
src/test/java/io/debezium/connector/yugabytedb/transforms/PGCompatibleTest.java

Add a transform to generate the event in PG Compatible schema

Add PGCompatible Transform

---

Jenkinsfile
pom.xml

* Build main branch
* Pushes the artefacts to s3

Added Jenkinsfile

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java

This PR contains a fix and a test as well for the issue #50.

Fix a bug which may cause Kafka Connect process crash

---

.github/workflows/sanity-workflow.yml
pom.xml
src/main/java/io/debezium/connector/yugabytedb/transforms/PGCompatible.java
src/test/java/io/debezium/connector/yugabytedb/transforms/PGCompatibleTest.java

PGTransform has to transform schemas even if value is NULL. 
PGTransform inherits optional/required attribute correctly.

PGCompatible Transform should recurse payload

---

pom.xml
src/main/java/io/aiven/kafka/connect/transforms/ExtractTopic.java
src/main/java/io/aiven/kafka/connect/transforms/ExtractTopicConfig.java
src/test/java/io/aiven/kafka/connect/transforms/ExtractTopicConfigTest.java
src/test/java/io/aiven/kafka/connect/transforms/ExtractTopicKeyTest.java
src/test/java/io/aiven/kafka/connect/transforms/ExtractTopicTest.java
src/test/java/io/aiven/kafka/connect/transforms/ExtractTopicValueTest.java

Refer: https://github.com/aiven/transforms-for-apache-kafka-connect#extracttopic

Add Extract topic Transformation

---

.github/workflows/sanity-workflow.yml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTablePoller.java
src/test/java/io/debezium/connector/yugabytedb/HelperStrings.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/resources/yugabyte_create_tables.ddl

This PR contains the diff to use a docker image as specified in the environment variable. The variable picks up the version from a stored GitHub action secret.
Additionally, it contains two more fixes to the test infrastructure:
1. Fail the tests if they are stuck for more than 5 minutes
2. Fix for a failing test because incorrect insert string was being used

[#73] GitHub actions stuck while running the tests

---

pom.xml

Upgrade dependencies to solve CVE vulnerabilities

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTabletSplitTest.java

1. Changes to include the API changes for `YBClient#getTabletListToPollForCDC`
2. Test addition to verify a data loss scenario in case of automatic tablet splitting.
Additionally, this PR closes issue [#79]

[#79] Changes for the modified API: `YBClient#getTabletListToPollForCDC`

---

pom.xml

[#90] Reverted a whitespace change

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorTask.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTaskContext.java

Use the constructor with the specified task ID

---

pom.xml

Bumping up yb-client version to reflect latest changes

---

Dockerfile
metrics.yml

Added the jmx agent to the Dockerfile along with metrics.yml which specifies the patterns to expose the metrics.

Added jmx agent and metrics pattern file

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java

This PR closes #100 and closes #101 too.

Add log and change config values

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBErrorHandler.java

[#88] Added logging around potential null pointers

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Refactor metronome initialization

---

pom.xml

Updating jars to fix CVE vulnerabilities

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBErrorHandler.java

Do not retry after task level retries are over

---

Dockerfile

This PR updates the JMX agent to the latest version.

[#126] Updated JMX agent to latest version

---

src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

This PR adds the unit test required in #134

Unit test to update primary key to same value

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Retry mechanism around the call to `GetTabletListToPollForCDC` while handling tablet split

---

pom.xml

[#152] Change module name to `YugabyteDB Source Connector`

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

[#143] Set initial checkpoint and cdcsdkSafeTime before snapshot

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/consistent/Merger.java

This PR changes the yb-client version to the one from S3.
PS. A minor typo is also fixed.

[#148] Change in yb-client version

---

.github/workflows/sanity-workflow-preview.yml

This PR adds a workflow which will be used to run tests against the preview builds of YugabyteDB.

[#157] Added workflow to be run against YugabyteDB preview builds

---

src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

This PR moves all the snapshot related tests to a new class and closes #145

[#145] Refactor snapshot related tests to a new class

---

src/test/java/io/debezium/connector/yugabytedb/rules/YugabyteDBLogTestName.java

[#197] Make test start and end markers more identifiable in logs

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

[#196] Upgrade yb-client versions to latest

---

Jenkinsfile

[#207] Upgraded YugabyteDB version to run tests in Jenkins

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This closes yugabyte/yugabyte-db#16058

[yugabyte/yugabyte-db#16058] Set tablet safetime parameter in the GetChanges request

---

src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java

This PR adds a test which verifies that inserting a null value in a table works fine and doesn't cause any issues.

Add test to verify the function of null values

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java

This PR has the following changes:
1. Refactor for a code section into a method to improve readability.
2. Conversion of one `HashMap` to `ConcurrentHashMap`
3. Adding method to `OpId` to verify equality with `CdcSdkCheckpoint`

Refactor wait code section into methods

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR simply modifies some logs and changes other logs levels to correctly log more information useful for debugging in case of failures and unexpected behaviour because of the results of the `GetTabletListToPollForCDC` RPC.

Logging improvements around `getTabletListToPollForCDC`

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This diff simply fixes one syntactical error introduced in #279 causing the compilation to fail.

Fix for compilation error because of logging changes

---

src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Some of the calls to the rpc getTabletListToPollForCDC did not have retry mechanisms. This Pr adds the required retries.

[yugabyte/yugabyte-db#12751] Added retries for getTabletListToPollForCdc Call

---

src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java

Service can send an empty list of tablets for a given table in case there are some issues there itself. In that case, if we proceed the connector tasks like that, we will end up getting errors further.
This PR adds a logic which leads to a retry whenever the connector detects that the API call for `GetTabletListToPollForCDC` has returned an empty list i.e. `resp.getTabletCheckpointPairListSize() == 0`

[yugabyte/yugabyte-db#19428] Retry `GetTabletListToPollForCDC` if the received list is empty

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR modifies some log levels as well as removes a duplicate logs causing huge log files.

Logging changes to improve debugging experience

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorTask.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTypeRegistry.java

This PR adds retry mechanism for operations involving YugabyteDBConnection. For every retry a new jdbc connection is created.

[yugabyte/yugabyte-db#12751] Added retries for YugabyteDBConnection

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTablePoller.java

Ensure that YBClient is closed properly in case of failures, stop, restart

Close YBClient in in case of shutdown

---

src/main/java/io/debezium/connector/yugabytedb/PgOid.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBCQLValueConverter.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSchema.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCQLTest.java

This PR adds support for decoding decimal and varint datatypes for cql tables

[yugabyte/yugabyte-db#19726] Added support for decoding decimal and varint datatypes for cql tables

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

Reverts yugabyte/debezium-connector-yugabytedb#328

Revert "Use configuration to log every GetChangesRequest"

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR changes the log level at which the connector logs the actual records and some metadata related to them from `DEBUG` to `TRACE` level.

[DBZ] Changed log level for records to `TRACE`

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Reverts yugabyte/debezium-connector-yugabytedb#340

Revert "[DBZ] Changed log level for records to `TRACE`"

---

pom.xml

This PR fixes the vulnerabilities by upgrading the dependency versions.

[DBZ] CDCSDK: Fixed vulnerabilities by upgrading dependency versions
