src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorIT.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

The ideal behaviour in case of TestContainers was when the test for a file are completed, the container should get cleaned up. However, in some cases, it was noticed that the cleanup is slow and the execution of the next test file begins before the container is cleaned up which leads to a situation where a new container fails to initialize.
This PR has the diff to fix the test failure issue.

Fix for intermittent test failures

---

pom.xml
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorIT.java

This PR has the diff for:
* The fix of an issue which was because of a missing `static` keyword for a function while running integration tests
* Refactoring a bunch of similar tests under a different file so that the tests can be run smoothly
* Changing the port for the existing IT to run.

Fix for a test issue causing IT test failure

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/transforms/YBExtractNewRecordState.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

The "YBExtractNewRecordState" transform was interfering with the below two configurations: 
```
delete.handling.mode=rewrite
drop.tombstones=false
```
By dropping the field "__deleted" from the source record. 
This change rectifies the behaviour of "YBExtractNewRecordState". 
Specifically, now YBExtractNewRecordState will not drop non-Struct fields from the source recrod.

Fix YBExtractNewRecordState transform to not drop non-Struct fields

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/resources/log4j.properties

This PR aims at increasing test coverage by adding unit test cases to validate the connector configuration, basically to provide a sanity test scenario. Additionally, the following changes are there as well:
* Addition of test to verify proper error message in case a null or empty stream ID is provided --> #6 
* Addition of test to verify the exception thrown and error message in case an empty `table.include.list` is provided --> #17 
* Removal of the configuration which allowed the connector to automatically create a DB stream ID

Test additions and improvements

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

A info log line needs to be pushed down to debug level since it will hog up the logs with unnecessary extra lines. This PR aims to make the same change.

Changing an info log to debug level

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java

After upgrade to debezium version `1.9.5.Final`, it was observed that the connector was not being deployed and threw error:
```
the config 'heartbeat.action.query' have been defined twice.
```
This PR contains a fix for the above mentioned issue.

Fix for connector crash while deploying

---

pom.xml

Adding a couple of dependencies which seemed to be missing from the core fat jars after upgrading to upstream version `1.9.5.Final`.

Fix for failed GitHub action runs

---

Dockerfile

Upgraded the Dockerfile to use a base image which is created using the latest Debezium release `debezium/connect:1.9.5.Final`.

Upgrade base image to be in sync with latest Debezium release

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/snapshot/InitialOnlySnapshotter.java
src/main/java/io/debezium/connector/yugabytedb/snapshot/InitialSnapshotter.java

With this change, the user would not need to change the snapshot mode from `initial` to `never` in order to further stream the changes.
Now, if the connector is deployed with `snapshot.mode=initial`, it would first take the snapshot and then would automatically switch to streaming new changes in the source database.

Implementing the transition from snapshot to streaming

---

Dockerfile

The updated base image out of which we are now creating our custom image will now have the PostgreSQL JDBC Driver as well to assist in replication to a Postgres sink using the JDBC Sink Connector.
Additionally, this PR also closes issue #43

Updating the base image in Dockerfile

---

src/main/java/io/debezium/connector/yugabytedb/transforms/PGCompatible.java
src/test/java/io/debezium/connector/yugabytedb/transforms/PGCompatibleTest.java

Implement a transform to make the event compatible with Postgres CDC Record Structure. 
It collapses `value` and `set` in a column record structure.

Add PGCompatible Transform

---

pom.xml

This PR is to update a dependency to a version which had the patch containing the fixes for a vulnerability raised by [Dependabot](https://github.com/yugabyte/debezium-connector-yugabytedb/security/dependabot/9).

Updating protobuf-java dependency version

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java

This PR closes issue #75 by changing the default polling interval at which the thread polls to check if there are any new tables added to the stream.

[#75] Increase default polling interval for new table poller thread

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTablePoller.java

The objective of this PR is to add the logic where if the new table poller thread sees a new table, it also verifies if the table is a part of the include list - if it is, only then signal the reconfiguration.
Additionally, this PR closes issue #76.

[#76] Only restart if the newly found table is a part of the include list

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorTask.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Previously, when we caught a  InterruptedException exception in the method: getChanges2
We were simply printing the stack trace and moving on. Now if one of the task in the execution service throws an 'InterruptedException' , we will kill all the tasks. 
Also adding minor logging changes: 
1. Every log from a task will also pint the task_id as part of the context
2. When we encounter an exception through 'GetChanges', we will also print the tablet causing the exception

Kill all tasks when we catch InterruptedException, minor logging changes

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR adds the change so that the connector also logs the `GetChanges` requests at regular intervals so that we know that the tasks are active and requesting for changes actively.

Log GetChanges request at 5 minutes intervals

---

src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBChangeRecordEmitter.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorTask.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTaskContext.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java

The changes introduced in this PR are all towards processing the before image of the row. Before this PR, when encountered an `UPDATE` op, and the function `getOldColumnValues()` was being called, we simply returned a `null` value assuming that since we are not even publishing the old value in our change record from server side, why even bother processing it.
With the latest changes on server side made to enable old image / before image of the changed row, we now publish them with the change records from the server and in that case, when we call `getOldColumnValues()`, the function should be able to process the messages properly in case of an update operation and hence the change in the mentioned function.
Now, as an optimization for the default cases, where the stream ID is not …

[#82] Support for publishing before image of the row

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR reorders the logic in which tablet split is handled.
Before this, we were handling tablet split in the order:
1. Remove parent tablet from polling list
2. Get child tablets and add them to the list
In case step 2 failed and we went for a retry, we will not be left with the parent tablet in the list since it has been removed. So the order has changed now to:
1. Get child tablets for the parent
2. Remove the parent tablet from polling list
This will ensure that if the API to fetch child tablet fails for some reasons, we are not left with no option to get the parent further.

[#111] Refactored the order of logic to handle tablet split

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBChangeRecordEmitter.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSchema.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

After a tablet has been split, we need to explicitly mention the flag in the GetChanges call so that the server sends the schema for the child tablet and we register it for further processing. This PR implements the same.

Request schema from the server once we start polling for child tablets

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

There is a log which prints whether we are requesting for schema for a particular tablet. The log can come up to as much as as half a million times if the connector is started and no record has been inserted into the table for a long time since we will keep requesting the schema and we will only receive it the first time our `GetChanges` call returns some records as well.
This PR changes the log level to debug so that we do not end up hogging the log.

Change a logging level to debug

---

Dockerfile

Before this, we used a base image with all the required dependencies (jars) which can then be used further by the image. This PR modifies the Dockerfile so that the process now downloads the jar files directly to the image while building. This PR closes #131

Change Dockerfile to download the required dependencies

---

Dockerfile

This PR uses one lower version for the mysql connector since the URL for the earlier file was broken. This also fixes https://github.com/yugabyte/yugabyte-db/issues/15498

Fix to download mysql connector jar from proper URL

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

This PR includes these changes:
1. Before starting the snapshot, set the checkpoint with `0,0` instead of `-1,-1`
2. For confirming whether the snapshot is completed, only check for the `key`, `write_id` and `snapshotTime`
3. The first GetChanges call to request the snapshot has the `snapshotTime` set to 0
This closes https://github.com/yugabyte/yugabyte-db/issues/15514

Snapshot bootstrap phase changes

---

src/test/java/io/debezium/connector/yugabytedb/consistent/YugabyteDBStreamConsistencyTest.java

This PR adds the ability to the consistency tests to be run against the docker image so that no local YugabyteDB instance is needed.

[#148] Ability to run consistency tests against YugabyteDB docker image

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDbConsistentStreaming.java
src/main/java/io/debezium/connector/yugabytedb/consistent/Merger.java

This PR adds the diff which will directly get the DDL records dispatched and not let them get added to the merger.

[#148] Ignore DDL records while adding to merger

---

pom.xml
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorIT.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBPartitionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSchemaEvolutionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTabletSplitTest.java
src/test/java/io/debezium/connector/yugabytedb/connection/YugabyteDBConnectionIT.java
src/test/java/io/debezium/connector/yugabytedb/transforms/PGCompatibleTest.java

This PR migrates all the tests from the junit-vintage-engine (JUnit4) to the junit-jupiter-engine (JUnit5). Additionally, this closes #59

Migrate tests to JUnit5

---

pom.xml
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorIT.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBPartitionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSchemaEvolutionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTabletSplitTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java
src/test/java/io/debezium/connector/yugabytedb/rules/YugabyteDBLogTestName.java

Log test names at the start of every test in order to make debugging easier in case of failures by figuring out the exact test name from the log files.
Closes #181

[#181] Log test names with each test

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java

The issue arose where we were checking whether the `OpId` is the snapshot complete marker on the `from_op_id` i.e. `cp` in our case - that is prone to errors as reported in stress tests as we may end up calling `GetChanges` with a checkpoint meant for streaming.
One such error occured in the call as mentioned in the ticket yugabyte/yugabyte-db#16556, on investigation, it was found that the flow was like:
1. Call `GetChanges` on `from_op_id` (for snapshot)
2. Receive a end marker in response and update the LSN
3. Since we were checking for snapshot end marker on `from_op_id` - it got ignored
4. The LSN now would not be the one we need to use for, but instead it would be the one being used for streaming
5. Now if we call `GetChanges` and if the tablet got split, we will throw a "tablet …

[CDCSDK#16556] Check for snapshot completion after GetChanges call

---

src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBExplicitCheckpointingTest.java
src/test/java/io/debezium/connector/yugabytedb/annotations/PreviewOnly.java
src/test/java/io/debezium/connector/yugabytedb/annotations/StableOnly.java
src/test/java/io/debezium/connector/yugabytedb/annotations/conditions/RunOnPreviewOnly.java
src/test/java/io/debezium/connector/yugabytedb/annotations/conditions/RunOnStableOnly.java

This PR adds two annotations `@PreviewOnly` and `@StableOnly` which will ensure that the test execution only happens against the build it is meant for. Eg.
* `@PreviewOnly` - for tests to be run against the preview builds of YugabyteDB
* `@StableOnly` - for tests to be run against the stable builds of YugabyteDB only
If no annotation is specified, the test will be run against both builds.
This PR closes #180

[#180] Add test annotations for testing against a specific build only

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotMidwayTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotResumeTest.java

Before this PR, if snapshot gets aborted in the middle for any reason and if the connector is restarted, it will start the snapshot from the beginning.
This PR changes the way snapshot is resumed, basically we persist the snapshot key on the server and once the connector is started, we check whether the server has any `snapshot_key` stored on the server - if yes, then we resume the snapshot from that point onwards only.
This also closes #205

[#205] Start snapshot from the key received in GetCheckpointResponse

---

src/main/java/io/debezium/connector/yugabytedb/transforms/StriimCompatible.java
src/test/java/io/debezium/connector/yugabytedb/transforms/StriimCompatibleTest.java

Create a transformer so that the records sent to kafka are compatible with [striim](https://www.striim.com/docs/en/postgresql-cdc.html#UUID-bb4c7685-acc1-6f6a-f4a2-afbfecf4febf).
**metadata (struct)** 
- LSN: log sequence number of the transaction's commit
- NEXT_LSN: next log sequence number (used for reconnecting to the replication slot after a non-fatal network interruption)
- OperationName: INSERT, UPDATE, or DELETE
- PK_UPDATE: included only when an UPDATE changes the primary key
- Sequence: incremented for each operation within a transaction
- TableName: the name of the table including its schema
- TimeStamp: timestamp from the replication subscription
- TxnID: transaction identifier
**data (array)**
- for an INSERT operation, the values that were inserted
- for an UPDATE, the …

[#200] Add a transformer for Striim compatibility

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/SourceInfo.java
src/main/java/io/debezium/connector/yugabytedb/YBPartition.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBChangeEventSourceCoordinator.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBChangeRecordEmitter.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/metrics/YugabyteDBSnapshotTaskMetrics.java
src/main/java/io/debezium/connector/yugabytedb/metrics/YugabyteDBStreamingTaskMetrics.java
src/main/java/io/debezium/connector/yugabytedb/util/YugabyteDBConnectorUtils.java
src/test/java/io/debezium/connector/yugabytedb/HelperStrings.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBExplicitCheckpointingTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
src/test/java/io/debezium/connector/yugabytedb/util/YugabyteDBConnectorUtilsTest.java
src/test/resources/yugabyte_create_tables.ddl

This PR changes the mechanism with which we store the OpIds, OffsetContext, SourceInfo and all the related things. Before this, they were keyed against the `tabletId` but this change modifies the logic so that they can be queried with `tableId.tabletId`. This will also help us in accommodating the changes for streaming the snapshot for colocated tables.
For example:
**Older logic:***
```
tablet_1 : op_id_1,
tablet_2 : op_id_2
```
**New logic:**
```
table.tablet_1 : op_id_1,
table.tablet_2 : op_id_2
```
The major changes in this PR (in no specific order) are:
1. Lookup of data using `tableId.tabletId` key
2. Sending a `snapshot_done_key` just once in the `GetChanges` call after we receive the snapshot complete marker from the server
3. Modification of existing snapshot tests to make them …

[#194] Store OpIds and offset contexts against a lookup key

---

metrics.yml

This PR modifies the regex to use the partition id instead of just tablet id which we further use to scrape Debezium metrics for Prometheus.
This closes yugabyte/yugabyte-db#16905

[yugabyte/yugabyte-db#16905] Fix metrics regex 

---

src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBRestartTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTabletSplitTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java
src/test/java/io/debezium/connector/yugabytedb/common/YugabyteDBContainerTestBase.java
src/test/java/io/debezium/connector/yugabytedb/common/YugabytedTestBase.java
src/test/java/io/debezium/connector/yugabytedb/container/CustomContainerWaitStrategy.java
src/test/java/io/debezium/connector/yugabytedb/container/YugabyteCustomContainer.java

This PR adds the method to restart the `yugabyted` process inside the YugabyteDB container. There are 3 methods added to facilitate the process related operations:
1. `stopYugabyteDB()` - stops the yugabyted process
2. `startYugabyteDB()` - starts the yugabyted process
3. `restartYugabyteDB(long)` - restarts the yugabyted process with a wait of specified milliseconds between stopping and starting the process.
A test has also been added to ensure that the APIs are functioning as expected, to run the test, use the command:
```
mvn clean test -Dtest=YugabyteDBDatatypesTest#verifyConsumptionAfterRestart
```
To achieve this, the following changes have been made:
1. Container now starts with a command for infinite loop - this ensured that even if we stop the `yugabyted` process, we do not end …

[yugabyte/yugabyte-db#16929] Add method to implement yugabyted restart

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBEventDispatcher.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTransactionContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBTransactionMonitor.java
src/main/java/io/debezium/connector/yugabytedb/connection/pgproto/YbProtoReplicationMessage.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTransactionMetadataTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java
src/test/resources/drop_tables_and_databases.ddl

This PR adds the following changes:
1. Addition of new classes to manage transactions i.e. `YugabyteDBTransactionContext` and `YugabyteDBTransactionMonitor`
a. Transactions are now monitored at the partition level and are identified by the `partition_id`
b. The implementation assumes that if two transactions get committed, we will only be seeing records in the order `begin_1` --> `commit_1` --> `begin_2` --> `commit_2`  
3. Addition of tests to verify the functioning of the transaction related classes to ensure that the transactional records are getting published to the respective topic with proper metadata. The tests added are:
a. Basic publishing of data
b. Data being published to a configurable topic
c. Data for multiple transactions is coming in order
d. Data for multiple tablets …

[yugabyte/yugabyte-db#16563] Send transaction metadata to the transaction topic properly

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBExplicitCheckpointingTest.java

This PR fixes a bug with explicit checkpoint and tablet splitting wherein let's say a tablet got split and the children got split further, but we haven't received a callback from Kafka about the parent record, in this case no explicit checkpoint was being marked on the `cdc_state` table thus leading us to in a error:
```
The logs from index -1 have been garbage collected and cannot be read
```
The fix to this is to detect that when we receive the tablet split message, then check if we have received the explicit commit callback as well, if we have then handle the split normally, if not then we proceed to add a tablet to a wait list so that we can pause polling on it for a while till the time we do not receive explicit commit callback.
This closes yugabyte/yugabyte-db#16946

[yugabyte/yugabyte-db#16946] Handle tablet split scenario with explicit checkpointing

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR modifies the error string wherein we were printing the error message and adds the full stacktrace instead of just calling the method `exception.getMessage()` to get the message.
This closes yugabyte/yugabyte-db#17541

[yugabyte/yugabyte-db#17541] Log full exceptions instead of just message

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorIT.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBPartitionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSchemaEvolutionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotResumeTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTabletSplitTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTransactionMetadataTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java

This PR modifies the following things:
1. Converts all tests to use EXPLICIT checkpointing
a. Added custom engine implementation to use a record committer
b. Overridden some test functions because the super class members were `private`
2. Fixed an error faced while running tests for snapshot with explicit checkpointing

[yugabyte/yugabyte-db#17551] Make all tests in the connector use explicit checkpointing

---

src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java

After recent changes where we migrated all the test infra to use explicit checkpointing, it was observed that in the infra was returning inconsistent consumed records intermittently.
Upon investigation, it was discovered that the queue we are using to hold the records can only hold certain number of records at a time which was the culprit. This PR adds a fix by removing the upper limit on the count of records.
Additionally, this closes #222

[#222] Fix test infra error of not consuming records

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/pgproto/YbProtoColumnValue.java
src/main/java/io/debezium/connector/yugabytedb/connection/pgproto/YbProtoReplicationMessage.java

This PR uses an additional parameter called `walSegmentIndex` while calling the API to get the changes.
For testing of this PR, consistency tests have been run separately to make sure we are getting records properly.

Add `walSegmentIndex` parameter while requesting changes

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java

A guard logic was added in a previous PR #236 to forcefully use the checkpoints being sent by the service. However, in case of colocated tables, the guard caused issues causing the connector to request changes from an `OpId` previous than what was checkpointed.
This PR removes the guard logic causing the issues. Also tracking probable issues in the ticket https://github.com/yugabyte/yugabyte-db/issues/18050 for later discussions around this.
Run the complete test suite.

Remove guard logic of using the checkpoints sent by server

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

Consider the scenario where we have 3 colocated tables, we start streaming for 2 of them.
1. We have 3 colocated tables
2. Start streaming with 2 of them in the include list
3. Stop the connector
4. Modify the configuration to include all 3 tables in the list now
In the above case, if there is an insert between step 3 and step 4, there will be data loss for colocated tables.
This PR adds the logic for the connector to send `snapshot_done_key` before the beginning of streaming in `snapshot.mode:never` so that the service knows the connector will not request snapshot in that case.
Modify an existing test case `YugabyteDBColocatedTablesTest#shouldWorkAfterAddingTableAfterRestart` to accomodate the scenario mentioned in the problem.
This PR closes yugabyte/yugabyte-db#18075

[yugabyte/yugabyte-db#18075] Send snapshot_done_key before starting streaming

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

In the method `commitOffsets()`, the logger takes its logging context from the Debezium Core library and since we are not setting any task ID there, nothing is printed as the task ID.
This PR adds a solution by leveraging a `taskContext` object accessible in the streaming and snapshot source classes and retrieves the task ID from that so that we can log it properly. This will be helpful in debugging callback and explicit checkpoint related failures.

Add task ID to the log statement while getting callback

---

src/main/java/io/debezium/connector/yugabytedb/SourceInfo.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBOffsetContext.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java

We will populate the last seen record's checkpoint in the "lastRecordCheckpoint" field. This is meant to have the explicit checkpoint details of the last seen record from any response (i,e the from_op_id and the record’s commit_time). We will try to update this value in every GetChanges call.
After “lastRecordCheckpoint” is updated as needed, we will then see the response checkpoint from the current GetChanges response. If the response checkpoint is higher :
1. We will store the response’s checkpoint, if the response’s checkpoint is higher than “lastReadRecordCheckpoint”
2. We will add this tablet to a wait-list, where we will first wait until the ExplicitCheckpoint of the tablet is equal to: “lastRecordCheckpoint”.
3. After the ExplicitCheckpoint was equal to “lastRecordCheckpoint”, then …

Explicit checkpoint wait on Tablet Split is now based on LastRecordCheckpoint

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

In one part of the code, we are calling the `GetCheckpoint` RPC on the service using `YBClient` - however, when the RPC fails, we do not have a mechanism to retry it or handle the exception at that level. This has consistently led to failure in the stress runs with exceptions similar to the following:
```
org.yb.client.CDCErrorException: Server[eea52488ba11431ba0d0dfcf2bdbd7b7] LEADER_NOT_READY_TO_SERVE[code 23]: Not ready to serve
```
This PR adds a retry logic to the RPC call so that if there are any failures, they are retried for a configured number of times before throwing the exception ultimately.
This PR is a part of the fix for yugabyte/yugabyte-db#18279

[yugabyte/yugabyte-db#18279] Retry logic for `GetCheckpoint` RPC

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java

It is possible for a transaction which is committed on a parent tablet that its `APPLY` records are distributed on both the children tablets after split. Now this `APPLY` record can have a lower commit time than the change records we receive from the parent tablets.
So after https://phorge.dev.yugabyte.com/D25399 was merged, if we do not reset the time for children tablets, we will end up filtering some records and end up in a data loss situation.
While adding the children tablets for polling, we are now simply resetting/unsetting the time back to 0 so that when the first `GetChanges` call happens, it uses this default value only.

Unset time from children tablets upon initialization

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/SourceInfo.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java

Today, in order to check if a tablet has empty snapshot, we just rely on the response size i.e. `GetChangesResponse` will have an empty record list, or in other terms a list of size 0. However, this logic is not enough for all the conditions where we genuinely can have empty responses, for example:
1. The first `GetChanges` call in cases of snapshot - this is only used to bootstrap snapshot on service.
2. Empty responses because of network or intermittent service issues.
This PR adds the following changes to fix the problem described:
1. Adds a getter in `SourceInfo` to check if we haven't seen any record yet.
3. Disallows waiting for callback if the tablet has no data to snapshot, this is checked if the following conditions are met
a. The `OpId` in `GetChangesResponse` is the snapshot …

[yugabyte/yugabyte-db#18245] Use `lastRecordCheckpoint` to detect empty snapshot

---

Dockerfile
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java

1. There is a log line where we are accessing the `toString()` method on an object which can be null which in turn is throwing a `NullPointerException` with a similar stacktrace as
```
Caused by: java.lang.NullPointerException
at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:398)
at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.execute(YugabyteDBSnapshotChangeEventSource.java:136)
... 9 more
```
2. Another issue is the reinitialisation of a set being used to store the list of tablets which should wait for callbacks. Over here, we have a set which is getting reinitialised in every iteration of the loop so the flow is something like:
```
Start Loop:
1. Initialise set
2. Add tablet list to the …
```

[yugabyte/yugabyte-db#18542] Fix NPE and incorrect reinitialisation of set

---

src/main/java/io/debezium/connector/yugabytedb/SourceInfo.java

Today, we publish the commit time values directly with the `source` object along with the message being published. However, this `commit_time` value is a hybrid time value and this will not be useful while comparing the time against a clock.
This PR adds the solution by borrowing the logic of conversion from service on how to convert hybrid time to physical time in microseconds and publishes the same value.
This also closes yugabyte/yugabyte-db#18512

[yugabyte/yugabyte-db#18512] Fix scale of the values published for `ts_ms` in `commit_time`

---

src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

Current Snapshot Tests do not have any test for testing out Snapshot in INITIAL_ONLY mode. In this PR two such tests have been added. The first one verifies the record count in both colocated and non colocated tables. The second one verifies that streaming records are not included in INITIAL_ONLY mode.

[yugabyte/yugabyte-db#18048]Added test for INITIAL_ONLY mode snapshot

---

Dockerfile

It was noticed that whenever cdc pipeline was run using the compiled jar for connector, the deployment of sink connectors failed. Upon investigation it was found that the kafka-connect-jdbc jar downloaded inside the Dockerfile was blank. This was caused because the curl commands in the Dockerfile which download the required jars did not have the `redirect` flag enabled.
The previous flow resulted in following error when trying to deploy sink connectors:
```
{"error_code":500,"message":"Failed to find any class that implements Connector and which name matches io.confluent.connect.jdbc.JdbcSinkConnector, available connectors are: PluginDesc{klass=class io.debezium.connector.db2.Db2Connector, name='io.debezium.connector.db2.Db2Connector', version='1.9.5.Final', encodedVersion=1.9.5.Final, …
```

[yugabyte/yugabyte-db#18655] Added the redirect flag for curl commands used to add Jars

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/YugabyteDBConnection.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java

Currently, the Debezium Connector for YugabyteDB takes in a `database.hostname` which is the IP of a node where the connector performs a one time operation to validate the user authentication.
This can create a problem as the current setup leads to a hard dependency on the provided node i.e. in case the connector restarts and the DB node crashes at that time then the connector will not be able to validate the connection and as a result of this, it will not proceed forward and fail at the validation step itself.
With this PR `database.hostname` config can now take in a comma separated addresses (ex `ip1:port1,ip2:port2, ip3:port3`) of multiple DB nodes. In case a node isn't available at the time of validation, the connector tries to connect to the next node. 
The earlier way of specifying …

[yugabyte/yugabyte-db#12751] Added support for multi node fail over connection

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

We were seeing `CDCSDK Trying to fetch already GCed intents for transaction 86630649-7302-45aa-a2ee-b46c01bdc8d7` on LRU test `test_cdc_lru_nemesis_splitting_postgres_debezium`
Analysis of VLOGS points to the fact that when the connector was erroneously setting OpId lower than the one already available with it in the `tabletToExplicitCheckpoint` map.
So for that particular tablet, `op_id` has been set to an older value, but the checkpoint available to it before callback was already a newer one than this. Since it had a newer checkpoint before this callback, the intents before this (newer) checkpoint were already garbage collected. So when the `GetChangesForCDCSDK` function tries to process the intents for this tablet, based on an older `op_id`, it throws a `Trying to fetch already GCed …

[CDCSDK] Add check to ensure received OpID always more than older checkpoint

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java

The connector allows users to deploy with configuration where the maximum task size can be anything i.e. `tasks.max`, but in case of `transaction.ordering:true` this will lead to problems since the records will not be ordered correctly, thus causing further issues in downstream sinks.
This PR adds a guard logic which throws an error if the user tries to deploy a connector where `transaction.ordering` is set to `true` and `tasks.max` has any value other than `1`.

[yugabyte/yugabyte-db#18661] Throw error if incorrect task size specified with transaction ordering

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

While starting the streaming source, we first call the API `GetTabletListToPollForCDC` API to fetch the list of tablets in `cdc_state` along with their checkpoints. However, if a task restarts and some of the tablets have been split, we will still have the parent tablet in the original list, but the response would give us the current tablets (i.e. children tablets) - this would lead the connector to not find the given `parent_tablet` in the response and would ultimately cause a `NullPointerException`.
Throw a `RuntimeException` if we see that we are going to use any null value returned from the response method. Also add a message in the exception which indicates the user that they need to restart the connector in order to get past this.

Throw error if tablet is not found in the `GetTabletListToPollForCDCResponse`

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

The first GetChanges call in snapshot only tells the service to mark the snapshot boundary i.e. the snapshot is bootstrapped.  When snapshot is bootstrapped, the service marks certain `OpId` value in the `cdc_state` table to indicate snapshot end boundary.
Now if the connector fails just after the bootstrap GetChanges call and is restarted, it executes a `GetCheckpoint` RPC call to decide whether or not to take a snapshot, before this PR, the logic was solely based on the presence of a non-empty snapshot key and invalid checkpoint as follows:
1. If there is a non-empty snapshot key then snapshot is not completed and we need to continue taking snapshot, otherwise check for condition 2.
2. If the `OpId` is invalid i.e. term=-1 and index = -1 then take snapshot, otherwise the assumption is …

[yugabyte/yugabyte-db#19293] Modify logic to decide whether snapshot is complete

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Before this change, we parse the `CDCErrorException` and try to read the split tablet ID from the exception itself, but the parsing can not be relied upon and we will end up reading the wrong value as tablet ID.
Since we know what tablet the connector is polling on, we also know we will only get tablet split exception on the same, so we can use the same tablet ID as the split parent tablet ID while handling tablet split.

Do not read the split tablet ID from the exception message

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java

The setCheckpoint call in snapshot did not have proper retry mechanism in case of failure. As a result, in case of multi node connection when one of the node is down, the `setCheckpoint` call would fail.
Added the requirred retry mechanism for `setCheckpoint` call.

Added retry mechanism for setCheckpoint in snapshot

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java

Currently, the AsynClient retries an RPC for 100 times within an interval of almost one minute. This results in `Too many attempts` exception much before the specified time out is reached. 
This PR contains changes to add configurable maximum number of rpc retry attempts, while creating `AsyncClient`. The default number of retries have been set to a sufficiently large number, such that all the attempts will not get over much before the specified timeout.

[yugabyte/yugabyte-db#12751] Changes to add configurable rpc retry attempts

---

pom.xml

This PR upgrades the yb-client version used in the connector. This version of yb-client has fix for retry mechanism in case of  `CDCErrorException`

[yugabyte/yugabyte-db#19648] Upgrade yb-client version

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

The log line "Requesting changes from" is logged every time the connector makes an RPC call to get the changes from service. This, however, results in too many logs in the connector over a period of time and can be a bottleneck in terms of log size and logging costs.
This PR changes the log level to `DEBUG`. If run without DEBUG logs, we will only log the line at an interval of `log.get.changes.interval.ms` (default: 5*60*1000) which will work as an indicator that the task has some activity going on.

Make `GetChanges` logging only at the DEBUG level

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBCQLValueConverter.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCQLTest.java

There was a bug in the `convertString()` method of `YugabyteDBCQLValueConverter` because of which large input strings were getting truncated to the first 50 characters. This was due to the wrong `toString()` method being used for conversion of ByteString to String.
This issue was resolved by using `toStringUtf8()` instead of `toString()` method to extract the string from the ByteString. This PR also adds a test to verify the correct behaviour.

[yugabyte/yugabyte-db#19294] Resolved the issue of large input strings getting truncated

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/HelperBeforeImageModes.java
src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBChangeRecordEmitter.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java

Adding support for two new record types: `DEFAULT` and `NOTHING` based on Postgres replica identity types. Their behaviour for the basic queries listed below is as follows:
**Queries**:
```
CREATE TABLE t1(id INT PRIMARY KEY, v1 INT, v2 INT);
INSERT INTO t1 VALUES (1,2,3);
UPDATE t1 SET v1 = 3 WHERE id = 1;
DELETE from t1 WHERE id = 1;
```
| `RECORD_TYPE` | OPERATION | OLD_IMAGE | NEW_IMAGE  |
| ----------------- | ------------ | ------------ | -------------  | 
| `DEFAULT`           | UPDATE        | `{{}}`            | `{{1},{3},{3}}` |
|                               | DELETE        | `{{1}}`           | `{{}}`              |
| `NOTHING`          | UPDATE        | `{{}}`            | `{{1},{3},{3}}` |
|                               | DELETE        | `{{}}`            | `{{}}` …

[yugabyte/yugabyte-db#19260] Add support for NOTHING and DEFAULT on connector

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java

Current Behaviour:
Consider the case of colocated tables snapshot is to be taken on all tables. 
After snapshot bootstrap, if the connector restarts, `GetTabletListToPoll()` returns same `tablet_id` multiple times for a given colocated tableId. Due to this, after task division, same table-tablet pairs are added to a task config list multiple times . We filter out entries for snapshot using this task config list and store them in an ArrayList (`tableToTabletForSnapshot`). 
Finally, snapshot flow returns back successful status only when `snapshotCompletedTablets.size() == tableToTabletForSnapshot.size()`. This check never satisfies because `snapshotCompletedTablets` is a set, so it doesnt contain duplicate tablet entries and hence the connector is stuck in the snapshot flow.
Consider the …

[yugabyte/ygabyte-db#20052] Remove duplicate entries for colocated tables in the snapshot flow

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/HashPartition.java

After the connector changes for tablet split in this [commit](https://github.com/yugabyte/debezium-connector-yugabytedb/commit/78ab3261f2033be6753b58fbda81625d8fde7800), the connector tests on colocated tables have started failing. The test failures can be seen in `YugabyteDBColocatedTablesTest` and `YugabyteDBSnapshotTest` classes. This was identified as a regression for colocated tables.
We were relying on the `TabletLocationsPB` object to give us the table ID, however, in case of colocated tables, we only get the colocated parent id which is same for all the colocated tables and is not useful to us. This PR solves the problem by leveraging the table ID from the `YBTable` object and using the same to create the `HashPartition`
This closes yugabyte/yugabyte-db#20243

[yugabyte/yugabyte-db#20243] Fix regression in streaming colocated tables

---

src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotResumeTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
src/test/java/io/debezium/connector/yugabytedb/common/TestBaseClass.java

Consider this scenario:
Connector, in the snapshot phase, received the last batch of snapshot records. Since all the tablets were removed from the `shouldWaitForCallback` set right after the snapshot bootstrap call, connector will straight away send `snapshotDoneKey` even without waiting for Kafka to send callback for the last batch of snapshot records. Now if kafka had partially consumed the last batch of records and the connector restarted, the remaining records would be lost because connector when reading the cdc_state would conclude that snapshot has been completed on that particular tablet.  
This is fixed by #306 
Added new test `VerifyNoDataLossIfConnectorRestartDuringLastBatchConsumption` to reproduce the scenario. 
- Ran the test without fix in #306 and it fails when comparing …

Added test to repro data loss of last snapshot batch

---

src/test/java/io/debezium/connector/yugabytedb/consistent/YugabyteDBStreamConsistencyTest.java

This PR only adds a `tasks.max` configuration property to the consistency tests to ensure we have the configuration assertions working correctly.

Add max tax configuration property to test

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/SourceInfoTest.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCQLTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBColocatedTablesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBEnumValuesTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBExplicitCheckpointingTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBPartitionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSchemaEvolutionTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotResumeTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTabletSplitTest.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBTransactionMetadataTest.java
src/test/java/io/debezium/connector/yugabytedb/common/YugabyteDBContainerTestBase.java

Recently consistent snapshot streams have been introduced on the server side. All the connector tests currently run with the older streams. This PR provides support to run all the connector tests using older config model (`stream.id` and `table.include.list`) with the newly introduced consistent snapshot streams along with the older streams.

[yugabyte/yugabyte-db#20177] Support to run the connector tests with consistent snapshot streams

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/resources/drop_tables_and_databases.ddl
src/test/resources/yugabyte_create_tables.ddl

The connector was interpreting all the decimal values as `double` even if the mode was set to `precise` - this would have resulted in a loss of precision when streamed.
This PR disables the default form being set to `double` when the `decimal.handling.mode` is set to `precise`.

[yugabyte/yugabyte-db#20414] Fix loss of precision while interpreting as double

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBCompleteTypesTest.java
src/test/resources/drop_tables_and_databases.ddl
src/test/resources/yugabyte_create_tables.ddl

Original commit: 444d2de78d385b7bd4bfdada73c3076403e360a6 / #316 
The connector was interpreting all the decimal values as `double` even if the mode was set to `precise` - this would have resulted in a loss of precision when streamed.
This PR disables the default form being set to `double` when the `decimal.handling.mode` is set to `precise`.
This related to yugabyte/yugabyte-db#20414

[BACKPORT 1.9.5.y.33][yugabyte/yugabyte-db#20414] Fix loss of precision while interpreting as double

---

pom.xml

This PR contains the following changes:
* Upgrade of Kafka API version from `3.3.1` to `3.6.1`
* Removing the `latest` tag from the snapshot builds so that the snapshot releases do not get tagged with `latest` automatically
This closes yugabyte/yugabyte-db#20000

[yugabyte/yugabyte-db#20000] Upgrade Kafka API in dependencies

---

src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java
src/test/java/io/debezium/connector/yugabytedb/common/YugabyteDBContainerTestBase.java

With the commit https://github.com/yugabyte/yugabyte-db/commit/cade0a8688fea889f1595bfa0a15d61124849f0d we cannot use the IP `0.0.0.0` to start the `yugabyted` process as it will start a process on `127.0.0.1` of the Docker container and thus we will not be able to connect it from outside the container i.e. the test framework.
This blocks the execution of all the tests since the YugabyteDB container itself will not be starting up with this.
This PR implements a solution by leveraging the container IP address, so any RPC calls will be made to the container IP address.

Use container IP address to connect to YugabyteDB

---

src/main/java/io/debezium/connector/yugabytedb/YBClientUtils.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

This PR adds a log statement which prints the checkpoints for a given tablet just after it has been bootstrapped.

Log checkpoints for tablets after bootstrapping

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/metrics/YugabyteDBMetrics.java

This PR adds two configuration properties to make the process of MBean registration configurable:
* `mbean.registration.retries` - the number of attempts to retry upon a failure (default: 12)
* `mbean.registration.retry.delay.ms` - the number of milliseconds to wait before attempting a retry to register the MBean (default: 5000)

Make MBean registration retry attempts configurable

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

The connector flow today is such that:
1. Connector obtains the tablets from service
2. `HashPartitions` are created and the partition keys are passed down to the tasks
3. Tasks receive an immutable list of tablets and start processing that
4. In snapshot phase, connector directly rely on the passed list from the top level connector and take snapshot but in streaming phase it validates the tablet list again by asking the current tablets from service.
5. Now suppose if a tablet is split and connector is in streaming phase, connector will handle the split gracefully.
6. At this stage, if a task is restarted the flow will start from the snapshot phase itself and connector will try to get the checkpoint of tablets in the task to confirm whether to take snapshot. But the tablet list available …

[yugabyte/yugabyte-db#20636] Fetch for tablets from service in snapshot phase as well

---

pom.xml

In context of tablet splitting, we can arrive at a situation where the `YBClient` can host a `RemoteTablet` for a parent split tablet, the `RemoteTablet` in such cases does not have any active tservers. So when the method `getFirstTablet` will return us such `RemoteTablet` and `YBClient` will try to make the RPC call to it, the call would fail with a similar error (method and service names can vary depending on context):
```
org.yb.client.NonRecoverableException: Too many attempts: YRpc(method=GetTabletListToPollForCDC, service=yb.cdc.CDCService, tablet=null, attempt=1800, maxAttempts=1800, maxTimeoutMs=600000, elapsedTimeMs=6964)
```
This diff updates the version of yb-client which has a new method `getRandomActiveTablet` which iterates over the list of `RemoteTablet` and only returns a …

[yugabyte/yugabyte-db#20717] Update yb-client version to use latest changes

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/connection/OpId.java
src/main/java/io/debezium/connector/yugabytedb/connection/pgproto/YbProtoReplicationMessage.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotTest.java

1. Kafka topic is created with multiple partitions (2 in this example), let’s call them `partition_0` and `partition_1`
2. Connector takes snapshot
3. When the connector receives the last record of the last snapshot batch, it modifies its offset to `Long.MAX_VALUE` so that when Kafka executes a callback on this, we know that Kafka has received the last record of the snapshot process and we can transition to streaming.
4. But here’s the catch, suppose we have the second last record of the snapshot batch which has the offset `offset_second_last_record` and the last record’s modified offset is `offset_last_record`
5. Now even when the connector reads it in the correct order i.e. `second_last` and then `last`, since there are two partitions, there seems to be some kind of situation where the …

[yugabyte/yugabyte-db#20431] Publish last snapshot record again if callback not received

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
src/test/java/io/debezium/connector/yugabytedb/TestHelper.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

In the connector flow, we call `GetChanges` and then immediately set the tablet safe hybrid time from the response i.e. https://github.com/yugabyte/debezium-connector-yugabytedb/blob/main/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java#L533 
Now suppose there’s a case where connector faced some errors while publishing the records from this response and it threw an error, the error handling mechanism would attempt a retry on the `from_op_id` but this time the tablet safe hybrid time value would be higher thus resulting in filtering of some records which would cause data loss.
This diff moves the tablet safe time updation after the records have been processed successfully by the connector.
Closes yugabyte/yugabyte-db#21940

[yugabyte/yugabyte-db#21940] Update tablet safe hybrid time only after batch is processed

---

src/main/java/io/debezium/connector/yugabytedb/connection/HashPartition.java
src/test/java/io/debezium/connector/yugabytedb/connection/HashPartitionTest.java

The current check while validating tablet ranges uses assertions to validate the keys. According to [Oracle Java docs](https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html), assertions are disabled by default in a deployed application and hence we will never hit this assertion error even when there's a genuine issue.
This PR replaces the assertions with an `IllegalStateException` with a proper message to indicate whenever there's an error while validating whether or not we have received the tablets for the complete range.
This closes yugabyte/yugabyte-db#22550

[yugabyte/yugabyte-db#22550] Replace assertion while validating tablet ranges with IllegalStateException

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConsistentStreamingSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java

Consider the following scenario for a tablet:
1. Suppose our explicit checkpoint is at OpId `1.100`.
2. Now the connector streamed records till OpId `1.150`.
3. By this time, all the records are successfully published to Kafka but we have not received any callback yet.
4. There is a connector/task restart.
5. Connector will ask for the checkpoint from `cdc_state` table upon initialisation which will return `1.100` to us.
6. In the next `GetChanges` call, connector streams till OpId `1.110` and receives a callback with OpId `1.150` simultaneously.
7. We will end up marking the checkpoint in the `cdc_state` table as `1.150` - **note that from_op_id is still at 1.110**
8. If the background thread runs now, it will cleanup the intents till `1.150` and when the next `GetChanges` request will …

[DBZ] Keep explicit checkpoint lower than or equal to the request OpId

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorTask.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBSnapshotChangeEventSource.java

There are two bugs which were introduced when #348 and #352 were merged.
1. Wrong logic for the method `YugabyteDBConnectorTask#isTaskInSnapshotPhase`
```
protected boolean isTaskInSnapshotPhase() {
return (this.coordinator == null) && this.coordinator.isSnapshotInProgress();
}
```
The above logic will always return `false` indicating that the task is never in snapshot phase.
2. The method `YugabyteDBSnapshotChangeEventSource#getExplicitCheckpoint` does not consider the checkpoint for last record of last snapshot batch.
1. This PR fixes the method `YugabyteDBConnectorTask#isTaskInSnapshotPhase` by modifying the condition to use an `OR` operator.
2. For the method `YugabyteDBSnapshotChangeEventSource#getExplicitCheckpoint`, the condition is modified to check if the explicit checkpoint …

[DBZ] Bug fix for snapshot not transitioning to streaming

---

src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
src/main/java/io/debezium/connector/yugabytedb/YugabyteDBgRPCConnector.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBConfigTest.java

This PR disables the deployment of `YugabyteDBgRPCConnector` with `IMPLICIT` checkpointing streams.

[DBZ] Disable IMPLICIT checkpointing support in connector

---

src/main/java/io/debezium/connector/yugabytedb/connection/ReplicationMessageColumnValueResolver.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBBeforeImageTest.java

In the current implementation a bug exists in the ReplicationMessageColumnValueResolver class resolveValue() method due to which when a null value for Money type column is received by the connector we send a default value (0.00$) to the client. 
This PR fixes the bug by returning the appropriate value. Instead of returning the raw val we are now using the getter to return the correct value. The PGMoney class handles the null case thus solving the problem
This issue was first seen in the stress tests. The PR adds a test which reproduces the exact failure which was observed in stress test. In addition a second test is added to assert that for all the data types null values are being correctly sent by the connector.

[#25143] Fix issue with handling of null values for money type

---

src/main/java/io/debezium/connector/yugabytedb/connection/ReplicationMessageColumnValueResolver.java

In this [PR](https://github.com/yugabyte/debezium-connector-yugabytedb/pull/361), we replaced returning of the raw `val` with `getValue()` in ReplicationMessageColumnValueResolver class resolveValue() method for money type columns. This was done because in the case where money column contained null value the raw val returned was 0, resulting in 0.00$ value being sent to kafka.
However the getValue() returned a String as opposed to the double type `val` which was returned earlier. Though this fixed the behaviour with nulls, it broke the behaviour for non-nulls since YugabyteDBValueConverter could not work with String.
Instead of using `getValue()` from PGMoney class, return the `val` if the object is non-null. Return null otherwise.
The original commit which introduced this bug caused …

[#25143] Fix value resolver for money type columns

---

README.md

This PR changes the docker image versions in the README.md to latest ones.
This also fixes a typo which was there in the name of the connector class.

Fix README.md with correct connector class name and image versions

---

pom.xml
src/main/java/io/debezium/connector/yugabytedb/transforms/YBExtractNewRecordState.java
src/test/java/io/debezium/connector/yugabytedb/YugabyteDBDatatypesTest.java

The current behaviour with the connector is that a tombstone record is published immediately after the delete record (when tombstones are enabled), this tombstone record has the same `OpId` as the delete record. A rough flow looks like:
```java
queue.enqueue(deleteRecord);
if (tombstonesEnabled) {
queue.enqueue(tombstoneRecord);
}
```
Now there can be a situation where the connector crashes after adding the delete record to the queue and before it can add the tombstone record, it crashes or restarts - in that situation we might end up losing the tombstone record.
Since the tombstone record is essential to process delete records by some of the downstream connectors like the `io.confluent.connect.jdbc.JdbcSinkConnector` - these connectors will not be able to process deletes which would …

[yugabyte/yugabyte-db#27255] Modify YBExtractNewRecordState to introduce property "delete.to.tombstone"

---

pom.xml

- Updated protobuf version from 3.25.5 to 4.30.2
- Upgrade protobuf to the latest stable version for improved compatibility and features
- Existing tests should pass with the new protobuf version

Update protobuf version to 4.30.2
